In [1]:
import os 
from pathlib import Path

project_root = Path.cwd().parents[0]
os.chdir(project_root)
print("Set project_root:", project_root)

Set project_root: /home/sromo/Repos/lm-testbed


In [2]:
import re

text_path = project_root / "data/raw/the-verdict.txt"

with open(text_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

print(raw_text[:100])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g


In [3]:
text = "Hello world, this is a test!"

result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]

print(result)

['Hello', 'world', ',', 'this', 'is', 'a', 'test', '!']


In [4]:
preprocessed = re.split(r"([,.:?_!\"()\']|--|\s)", raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print("token length in text:", len(preprocessed))

all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print("vocab size:", vocab_size)

vocab = {token:integer for integer, token in enumerate(all_words)}
print(vocab)


token length in text: 4669
vocab size: 1143
{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Carlo;': 25, 'Chicago': 26, 'Claude': 27, 'Come': 28, 'Croft': 29, 'Destroyed': 30, 'Devonshire': 31, 'Don': 32, 'Dubarry': 33, 'Emperors': 34, 'Florence': 35, 'For': 36, 'Gallery': 37, 'Gideon': 38, 'Gisburn': 39, 'Gisburns': 40, 'Grafton': 41, 'Greek': 42, 'Grindle': 43, 'Grindles': 44, 'HAD': 45, 'Had': 46, 'Hang': 47, 'Has': 48, 'He': 49, 'Her': 50, 'Hermia': 51, 'His': 52, 'How': 53, 'I': 54, 'If': 55, 'In': 56, 'It': 57, 'Jack': 58, 'Jove': 59, 'Just': 60, 'Lord': 61, 'Made': 62, 'Miss': 63, 'Money': 64, 'Monte': 65, 'Moon-dancers': 66, 'Mr': 67, 'Mrs': 68, 'My': 69, 'Never': 70, 'No': 71, 'Now': 72, 'Nutley': 73, 'Of': 74, 'Oh': 75, 'On': 76, 'Once': 77, 'Only': 78, 'Or': 79, 'Perhaps': 

In [5]:
inverse_dict = {s:i for i,s in vocab.items()}

print(inverse_dict)

{0: '!', 1: '"', 2: "'", 3: '(', 4: ')', 5: ',', 6: '--', 7: '.', 8: ':', 9: ';', 10: '?', 11: 'A', 12: 'Ah', 13: 'Among', 14: 'And', 15: 'Are', 16: 'Arrt', 17: 'As', 18: 'At', 19: 'Be', 20: 'Begin', 21: 'Burlington', 22: 'But', 23: 'By', 24: 'Carlo', 25: 'Carlo;', 26: 'Chicago', 27: 'Claude', 28: 'Come', 29: 'Croft', 30: 'Destroyed', 31: 'Devonshire', 32: 'Don', 33: 'Dubarry', 34: 'Emperors', 35: 'Florence', 36: 'For', 37: 'Gallery', 38: 'Gideon', 39: 'Gisburn', 40: 'Gisburns', 41: 'Grafton', 42: 'Greek', 43: 'Grindle', 44: 'Grindles', 45: 'HAD', 46: 'Had', 47: 'Hang', 48: 'Has', 49: 'He', 50: 'Her', 51: 'Hermia', 52: 'His', 53: 'How', 54: 'I', 55: 'If', 56: 'In', 57: 'It', 58: 'Jack', 59: 'Jove', 60: 'Just', 61: 'Lord', 62: 'Made', 63: 'Miss', 64: 'Money', 65: 'Monte', 66: 'Moon-dancers', 67: 'Mr', 68: 'Mrs', 69: 'My', 70: 'Never', 71: 'No', 72: 'Now', 73: 'Nutley', 74: 'Of', 75: 'Oh', 76: 'On', 77: 'Once', 78: 'Only', 79: 'Or', 80: 'Perhaps', 81: 'Poor', 82: 'Professional', 83: 'Ren

In [6]:
from src.layers.simple_tokenizers import SimpleTokenizerV1

tokenizer = SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know,"
Mrs. Gisburn said with pardonable pride."""

tokens = tokenizer.encode(text)

print("tokens:", tokens)
print("decoded text:", tokenizer.decode(tokens))

tokens: [1, 57, 2, 861, 999, 610, 538, 754, 5, 1139, 603, 5, 1, 68, 7, 39, 862, 1121, 764, 803, 7]
decoded text: " It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


**Adding tokens to account for unkown words and endoftext**

In [7]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
vocab = {token:integer for integer,token in enumerate(all_tokens)}

print(vocab)
print("new vocab lenghth:", len(vocab))

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Carlo;': 25, 'Chicago': 26, 'Claude': 27, 'Come': 28, 'Croft': 29, 'Destroyed': 30, 'Devonshire': 31, 'Don': 32, 'Dubarry': 33, 'Emperors': 34, 'Florence': 35, 'For': 36, 'Gallery': 37, 'Gideon': 38, 'Gisburn': 39, 'Gisburns': 40, 'Grafton': 41, 'Greek': 42, 'Grindle': 43, 'Grindles': 44, 'HAD': 45, 'Had': 46, 'Hang': 47, 'Has': 48, 'He': 49, 'Her': 50, 'Hermia': 51, 'His': 52, 'How': 53, 'I': 54, 'If': 55, 'In': 56, 'It': 57, 'Jack': 58, 'Jove': 59, 'Just': 60, 'Lord': 61, 'Made': 62, 'Miss': 63, 'Money': 64, 'Monte': 65, 'Moon-dancers': 66, 'Mr': 67, 'Mrs': 68, 'My': 69, 'Never': 70, 'No': 71, 'Now': 72, 'Nutley': 73, 'Of': 74, 'Oh': 75, 'On': 76, 'Once': 77, 'Only': 78, 'Or': 79, 'Perhaps': 80, 'Poor': 81, 'Professional': 82, 'Renaiss

In [8]:
from src.layers.simple_tokenizers import SimpleTokenizerV2

tokenizer = SimpleTokenizerV2(vocab)
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(text)

tokens = tokenizer.encode(text)
print("tokens:", tokens)
print("decoded text:", tokenizer.decode(tokens))

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.
tokens: [1144, 5, 360, 1139, 636, 986, 10, 1143, 56, 999, 967, 995, 730, 999, 1144, 7]
decoded text: <|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


**Byte-pair encoding**

In [9]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")

text = (
"Hello, do you like tea? <|endoftext|> In the sunlit terraces"
"of someunknownPlace."
)
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

strings = tokenizer.decode(integers)
print(strings)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]
Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [10]:
# Tiktoken BPE tokenizer handles unkown words by breaking down into known tokens (i.e. letters, common letter groups)
text = "Akwirw ier"
integers = tokenizer.encode(text)
print(integers)

for integer in integers:
    print(integer, "-", tokenizer.decode([integer]))

[33901, 86, 343, 86, 220, 959]
33901 - Ak
86 - w
343 - ir
86 - w
220 -  
959 - ier


**Data sampling with a sliding window**

We need to generate the input-target pairs required for LLM training

In [11]:
text_path = project_root / "data/raw/the-verdict.txt"

with open(text_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print("encoded text length:", len(enc_text))

encoded text length: 5145


In [12]:
enc_sample = enc_text[:50]

context_size = 4
print(enc_sample)
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(f"x: {x}")
print(f"y:     {y}")

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11]
x: [40, 367, 2885, 1464]
y:     [367, 2885, 1464, 1807]


In [13]:
for i in range(1, context_size+1):
    x = enc_sample[:i]
    y = enc_sample[i]
    print(x, "-->", y)
    print(tokenizer.decode(x), "-->", tokenizer.decode([y]), "\n")

[40] --> 367
I -->  H 

[40, 367] --> 2885
I H --> AD 

[40, 367, 2885] --> 1464
I HAD -->  always 

[40, 367, 2885, 1464] --> 1807
I HAD always -->  thought 



**Testing our dataloader and tokenizer**

In [14]:
from src.dataloaders.GPT import create_dataloader_v1

with open(text_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)
data_iter = iter(dataloader)                                            # Converst dataloader into a Python itereator to use the built-in next() function
first_batch = next(data_iter)
print("first_batch:", first_batch)

second_batch = next(data_iter)
print("second_batch:", second_batch)


first_batch: [tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]]), tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])]
second_batch: [tensor([[  287,   262,  6001,   286],
        [  465, 13476,    11,   339],
        [  550,  5710,   465, 12036],
        [   11,  6405,   257,  5527],
        [27075,    11,   290,  4920],
        [ 2241,   287,   257,  4489],
        [   64,   319,   262, 34686],
        [41976,    13,   357, 10915]]), tensor([[  262,  6001,   286,   465],
        [13476,

**Creating token embeddings**

So far we have gotten our token id's, the next step is to ge the token embeddings

In [15]:
# Token ID to vector conversion example:
import torch
input_ids = torch.tensor([2,3,5,1])
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

token_id = 3
print(f"\nEmbedding vector for token_id {token_id}:")
print(embedding_layer(torch.tensor([3])))

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

Embedding vector for token_id 3:
tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [16]:
input_ids = torch.tensor([2, 3, 5, 1])
embedding_layer(input_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

**Encoding word positions**

Lets consider GPT-3's vocab_size and output_dim:

In [17]:
import torch
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(token_embedding_layer.weight)

Parameter containing:
tensor([[-2.1338,  1.0524, -0.3885,  ...,  0.2461,  1.2119,  0.3171],
        [ 1.2277, -0.4297, -2.2121,  ..., -0.1640, -0.3348, -0.0221],
        [ 1.3382,  0.2706,  0.5071,  ...,  0.0175, -2.1517,  0.3924],
        ...,
        [-1.4889, -1.2456,  1.8034,  ..., -0.6392, -1.4939,  0.3614],
        [-1.0703,  0.2795, -0.2637,  ..., -0.2810, -1.4755, -0.1183],
        [-0.0071,  0.4982, -0.3319,  ...,  0.4970,  0.9365, -0.2091]],
       requires_grad=True)


In [18]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
    )
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Token IDs:\n", inputs)
print("\nInputs shape:", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape: torch.Size([8, 4])


In [19]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [20]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [21]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
